kind: Deployment
apiVersion: apps/v1
metadata:
  name: ktni-actions
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ktni-actions
  template:
    metadata:
      labels:
        k8s-app: ktni-actions
    spec:
      containers:
      - name: ktni-actions
        image: registry.digitalocean.com/olsen/ktni-actions
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
  minReadySeconds: 5