apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: ktni-nginx
  rules:
  - http:
      paths:
      - path: app.motoren.site/ktni-actions
        backend:
          service: 
            name: ktni-service
            port:
              number: 80