apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ktni-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "app.motoren.site"
  - http:
      paths:
      - pathType: Prefix
        path: /ktni-actions
        backend:
          service: 
            name: ktni-actions
            port:
              number: 80