kind: Service
apiVersion: v1
metadata:
  name: ktni-actions
  namespace: apps
  labels:
    k8s-app: ktni-actions
spec:
  selector:
    k8s-app: ktni-actions
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  ipFamilyPolicy: SingleStack