kind: Service
apiVersion: v1
metadata:
  name: ktni-actions
  namespace: apps
spec:
  selector:
    app.kubernetes.io/name: ktni-actions
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP